### ISSUE TITLE
is it ready to use ?

### ISSUE THREAD

**Issue by MayurDivate** [cgplab/ddSeeker#1]
Hi Dario Romagnoli,

could not find the better way to ask this question.
Is your program read to use?
Can I use it ??

Mayur

**Comment by romagnolid** [comment]
Hi,
we are still testing it so there may be some bugs we haven't spotted yet but you can use it.

**Comment by MayurDivate** [comment]
okay thanks!

**Comment by MayurDivate** [comment]
I tried to run ddSeeker but could not succeed.

Here are the command and error.

python ~/Programs/ddSeeker/ddSeeker.py lib_293_3t3_unmapped.bam -o lib_293_3t3_tagged.bam -s unmapped_summary -n 10 
  File "/home/mdivate/Programs/ddSeeker/ddSeeker.py", line 19
    print(time.strftime("[%Y-%m-%d %H:%M:%S]"), file=stderr, *args, **kwargs)
                                                    ^
SyntaxError: invalid syntax

**Comment by romagnolid** [comment]
Probably your default python version is **2** but the package was written specifically for **python3**.
Try with
```
python3 ~/Programs/ddSeeker/ddSeeker.py lib_293_3t3_unmapped.bam -o lib_293_3t3_tagged.bam -s unmapped_summary -n 10
```
or as an executable
```
~/Programs/ddSeeker/ddSeeker.py lib_293_3t3_unmapped.bam -o lib_293_3t3_tagged.bam -s unmapped_summary -n 10
```
