### ISSUE TITLE
r graphs

### ISSUE THREAD

**Issue by ibseq** [cgplab/ddSeeker#4]
hello, I managed to run the first steps of ddsseker but I'm stuck at generating the r graphs. 
do you have more detailed step by step commands for running R? I tried even to run manually the  make_graphs.R but it seems there's something missing

thanks for the help 
ibseq

**Comment by romagnolid** [comment]
Hello Irene, do you get any error message?

**Comment by ibseq** [comment]
Hi Dario, 
Massive thanks for getting back to me

No error messages up to running :
1. ddSeeker.py --input sampleA_R1.fastq.gz sampleA_R2.fastq.gz --output sampleA_tagged.bam --cores 20
2. mkdir summary_folder
3. ddSeeker.py -i sampleA_R* -c 20 -o sampleA_tagged.bam -s summary_folder/sampleA


Now I’d like to see what’s the difference between my 4 samples - e.g. transcripts levels and some visual graphs but I’m not an R expert and all I tried to run was :
4. Rscript make_graphs.R summary_folder/sampleA 2000

But I don’t get any results

It's a test run and it would be great to know what these samples looks like

thanks
Irene

**Comment by romagnolid** [comment]
Can you send me your summary files? You can use my email.
Also, did you install the package "tidyverse"? If not, open R and enter `install.packages("tidyverse")`. It will take 10 minutes more or less.
