### ISSUE TITLE
high number of barcodes in quality report

### ISSUE THREAD

**Issue by LisaHagenau** [cgplab/ddSeeker#6]
Hi,
thanks for this software. I was running it on data from our first single cell sequencing run and noticed a very high number of identified barcodes (200,000+) in the quality report, despite limiting the number of barcodes to 2000. This is the command I used.
`make_graphs.R summarytest/S039 2000`
The quality of the run seems to be fine according to the high number of passed reads (see attachment). 
[testS039.pdf](https://github.com/cgplab/ddSeeker/files/4803148/testS039.pdf)
Is it normal that such a high number of barcodes is identified in the first place?
Thanks,
Lisa

**Comment by romagnolid** [comment]
Hello @LisaHagenau thank you for using it.
In our experience it's common to identify a very high number of barcodes (we got 500k barcodes in one of our experiments) though the majority of the signal belongs to a few thousands, as expected. It's strange that the script doesn't apply the filter. Could you send me the summary to make a test myself? It looks like a bug in our code.

**Comment by LisaHagenau** [comment]
Hi @romagnolid, thanks for the quick answer. I have attached the 2 csv files.
[summary.zip](https://github.com/cgplab/ddSeeker/files/4813727/summary.zip)

**Comment by romagnolid** [comment]
Hi @LisaHagenau , it worked for me. Can you check if you pulled the very last version? 
[S039.pdf](https://github.com/cgplab/ddSeeker/files/4814359/S039.pdf)

**Comment by LisaHagenau** [comment]
@romagnolid Updating to the last version did the trick. Thank you!

**Comment by romagnolid** [comment]
Glad to hear that :)

Il giorno mar 23 giu 2020 alle ore 14:12 LisaHagenau <
notifications@github.com> ha scritto:
